version: "3.3"

volumes:
  postgres:
  pgadmin:

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.8.0
    hostname: pgadmin
    restart: unless-stopped
    env_file:
      - ./env_files/pgadmin.env
    ports:
      - "8999:80"
    networks:
      guacnetwork_compose:
        ipv4_address: 172.29.0.3
    volumes:
      - pgadmin:/var/lib/pgadmin
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    container_name: postgres
    image: postgres:18.0-alpine3.21
    hostname: postgres
    restart: always
    env_file:
      - ./env_files/postgres.env
    environment:
      - TZ=Europe/Moscow
    networks:
      guacnetwork_compose:
        ipv4_address: 172.29.0.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./_data/postgres:/docker-entrypoint-initdb.d:z

  guacd:
    container_name: guacd
    hostname: guacd
    image: guacamole/guacd:1.6.0
    restart: always
    environment:
      - TZ=Europe/Moscow
    networks:
      guacnetwork_compose:
        ipv4_address: 172.29.0.5
    volumes:
      - ./_data/guacd/drive:/drive:rw
      - ./_data/guacd/record:/record:rw
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep :4822"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  guacamole:
    container_name: guacamole
    hostname: guacamole
    image: guacamole/guacamole:1.6.0
    restart: always
    depends_on:
      guacd:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - TZ=Europe/Moscow
    env_file:
      - ./env_files/guacamole.env
    networks:
      guacnetwork_compose:
        ipv4_address: 172.29.0.6
    volumes:
      - ./_data/guacamole:/etc/guacamole
      - ./_data/guacd/record:/record:rw
      - ./_data/guacamole/guacamole.properties:/etc/guacamole/guacamole.properties:ro
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/guacamole/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  guacamole_recordings:
    container_name: guacamole_recordings
    image: tomcat:10.1-jdk17
    restart: always
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8081:8080"
    networks:
      guacnetwork_compose:
        ipv4_address: 172.29.0.7
    volumes:
      - ./_data/guacd/record:/recordings:ro
      - ./_data/tomcat/conf/Catalina/localhost:/usr/local/tomcat/conf/Catalina/localhost:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/recordings"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      guacamole:
        condition: service_healthy
      guacamole_recordings:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      guacnetwork_compose:
        ipv4_address: 172.29.0.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/guacamole/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      




########################################################
  wireguard:
    image: linuxserver/wireguard:v1.0.20210914-ls6
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.100.0.0/24
    volumes:
      - ./_data/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
      - 5000:5000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=CyberDSTPASS
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - WGUI_SERVER_INTERFACE_ADDRESSES=10.100.0.1/24
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./_data/wireguard/db:/app/db
      - ./_data/wireguard/config:/etc/wireguard
    restart: always
########################################################



networks:
  guacnetwork_compose:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24